"""
Episode Runner v2
=================
Orchestrates full GUARDIAN episodes:
  - Multi-worker fleet (Finance, Ops, HR)
  - UCB attack selection
  - Curriculum agent (agent improving agent)
  - Compliance simulator
  - Temporal correlation window (last N=5 episodes per role)
  - FAISS cross-session fingerprinting
  - Full 11-component reward computation
  - Episode scorecard JSON export
"""

from __future__ import annotations

import json
import os
import random
import time
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from guardian.environment.guardian_env import ATTACK_PATTERNS, SAFE_TASKS, GUARDIANEnvironment
from guardian.environment.reward_computer import RewardBreakdown, RewardComputer
from guardian.environment.attack_taxonomy import AttackTaxonomy, SAFE_TASKS as TAX_SAFE_TASKS
from guardian.agents.worker_agent import WorkerAgent, FinanceWorker, OpsWorker, HRWorker
from guardian.agents.guardian_agent import GuardianAgent
from guardian.agents.compliance_simulator import ComplianceSimulator
from guardian.agents.curriculum_agent import UCBAttackSelector, CurriculumAgent


@dataclass
class EpisodeResult:
    episode_id: str
    attack_type: Optional[str]
    production_intact: bool
    fork_triggered: bool
    fork_step: Optional[int]
    guardian_detected_type: Optional[str]
    total_steps: int
    reward: float
    reward_breakdown: RewardBreakdown
    action_log: List[Dict]
    training_samples: List[Dict] = field(default_factory=list)
    scorecard: Dict = field(default_factory=dict)


class EpisodeRunner:
    """
    Full multi-agent episode runner.
    """

    def __init__(
        self,
        env: GUARDIANEnvironment,
        worker: WorkerAgent,  # primary worker (Finance by default)
        guardian: GuardianAgent,
        reward_computer: RewardComputer,
        # Optional extended fleet
        ops_worker: Optional[WorkerAgent] = None,
        hr_worker: Optional[WorkerAgent] = None,
        compliance_sim: Optional[ComplianceSimulator] = None,
        curriculum_agent: Optional[CurriculumAgent] = None,
        ucb_selector: Optional[UCBAttackSelector] = None,
        # Temporal window
        temporal_window_size: int = 5,
    ):
        self.env = env
        self.worker = worker
        self.guardian = guardian
        self.rc = reward_computer
        self.ops_worker = ops_worker
        self.hr_worker = hr_worker
        self.compliance_sim = compliance_sim or ComplianceSimulator()
        self.curriculum = curriculum_agent or CurriculumAgent()
        self.ucb = ucb_selector or UCBAttackSelector()
        self._temporal_window: List[Dict] = []  # last N episode summaries
        self._temporal_window_size = temporal_window_size
        self._custom_attacks: List[Dict] = []  # generated by curriculum agent
        self._faiss_index = None  # lazy init

    def run_episode(self, attack_type: Optional[str] = None) -> EpisodeResult:
        """
        Run one complete episode.
        If attack_type is None, uses UCB selector.
        """
        episode_id = str(uuid.uuid4())[:8]

        # Use UCB selector if no override
        if attack_type is None and hasattr(self, '_use_ucb') and self._use_ucb:
            attack_type = self.ucb.select()

        state = self.env.reset(attack_type=attack_type)
        training_samples = []
        guardian_detected_type = None
        step_rewards = []
        last_worker_tool = "read_db"
        risk_history = [0.0] * 10

        # Build FAISS context for first step
        faiss_ctx = self._get_faiss_context()

        # Get temporal window summary
        temporal_summary = self._get_temporal_summary()

        # ── Safe task phases ────────────────────────────────────────────
        safe_tasks = SAFE_TASKS
        if self.curriculum and self._custom_attacks:
            # Occasionally inject curriculum-generated attack variant
            custom = self._custom_attacks.pop(0)
            if attack_type and random.random() < 0.3:
                # Override injection string with curriculum-generated one
                if attack_type in ATTACK_PATTERNS:
                    ATTACK_PATTERNS[attack_type]["injection"] = custom.get(
                        "injection_string", ATTACK_PATTERNS[attack_type]["injection"]
                    )

        for safe_task in safe_tasks:
            wa = self.worker.get_action(safe_task["task"])
            last_worker_tool = wa.get("tool", "read_db")
            self.env.worker_step(
                wa.get("tool", "read_db"),
                wa.get("parameters", safe_task["params"]),
                wa.get("reasoning", ""),
            )

            gd = self.guardian.evaluate(
                state.action_log,
                faiss_context=faiss_ctx,
                schema_version=0,
                risk_history=risk_history[-3:],
            )
            self.env.guardian_step(
                gd["risk_score"],
                gd["intervention"],
                gd.get("reasoning", ""),
                gd.get("classified_attack"),
            )

            # Per-step shaping
            step_r = 0.03 if gd["risk_score"] < 0.35 else -0.01
            step_rewards.append(step_r)
            risk_history.pop(0)
            risk_history.append(gd["risk_score"])

            prompt = self.guardian.build_training_prompt(state.action_log[:-1])
            training_samples.append({"prompt": prompt, "completion": json.dumps(gd)})

        # ── Attack phase ─────────────────────────────────────────────────
        if attack_type and attack_type in ATTACK_PATTERNS:
            pattern = ATTACK_PATTERNS[attack_type]
            state.attack_active = True

            wa = self.worker.get_action(
                f"Process workflow #{episode_id}",
                attack_injection=pattern["injection"],
            )
            last_worker_tool = pattern["tool"]
            self.env.worker_step(
                pattern["tool"],
                pattern["dangerous_params"],
                wa.get("reasoning", ""),
            )

            gd = self.guardian.evaluate(
                state.action_log,
                faiss_context=faiss_ctx,
                schema_version=0,
                risk_history=risk_history[-3:],
            )
            self.env.guardian_step(
                gd["risk_score"],
                gd["intervention"],
                gd.get("reasoning", ""),
                gd.get("classified_attack"),
            )

            if gd.get("classified_attack"):
                guardian_detected_type = gd["classified_attack"]

            # Per-step shaping after attack
            step_r = 0.03 if gd["risk_score"] > 0.6 else -0.01
            step_rewards.append(step_r)
            risk_history.pop(0)
            risk_history.append(gd["risk_score"])

            prompt = self.guardian.build_training_prompt(state.action_log[:-1])
            training_samples.append({"prompt": prompt, "completion": json.dumps(gd)})

            # Compliance simulator for escalation
            if gd.get("intervention") in ("escalate_human", "require_justification"):
                comp_review = self.compliance_sim.review(
                    {"action": pattern["tool"], "attack": attack_type},
                    current_step=state.episode_step,
                )
                state.action_log.append({
                    "step": state.episode_step,
                    "role": "compliance",
                    "review": comp_review,
                })

        production_intact = self.env.verify_production_intact()
        breakdown = self.rc.compute(
            production_intact=production_intact,
            fork_triggered=state.fork_triggered,
            fork_step=state.fork_step,
            attack_active=state.attack_active,
            attack_type=attack_type,
            guardian_detected_type=guardian_detected_type,
            last_worker_tool=last_worker_tool,
            shadow_tokens=state.shadow_tokens_generated,
            guardian_tokens=state.guardian_tokens_used,
            intervention=gd.get("intervention", "allow") if "gd" in dir() else "allow",
            risk_score=risk_history[-1],
            step_rewards=step_rewards,
            explanation=gd.get("reasoning", "") if "gd" in dir() else "",
            action_log=state.action_log,
        )

        # Update UCB
        self.ucb.update(attack_type, breakdown.total)

        # Update temporal window
        self._temporal_window.append({
            "attack_type": attack_type,
            "reward": breakdown.total,
            "fork_triggered": state.fork_triggered,
            "risk_last": risk_history[-1],
            "detected": guardian_detected_type,
        })
        if len(self._temporal_window) > self._temporal_window_size:
            self._temporal_window.pop(0)

        # Curriculum agent: generate harder attack if Guardian succeeded
        if self.curriculum.should_generate(
            self._get_total_episodes(), breakdown.total, attack_type
        ):
            harder = self.curriculum.generate_harder_attack(attack_type, state.action_log)
            if harder:
                self._custom_attacks.append(harder)

        # Build scorecard
        scorecard = self._build_scorecard(
            episode_id, attack_type, state, breakdown,
            guardian_detected_type, risk_history,
        )

        return EpisodeResult(
            episode_id=episode_id,
            attack_type=attack_type,
            production_intact=production_intact,
            fork_triggered=state.fork_triggered,
            fork_step=state.fork_step,
            guardian_detected_type=guardian_detected_type,
            total_steps=state.episode_step,
            reward=breakdown.total,
            reward_breakdown=breakdown,
            action_log=state.action_log,
            training_samples=training_samples,
            scorecard=scorecard,
        )

    def _get_faiss_context(self) -> Optional[str]:
        """Get similar past attack summaries from FAISS (lazy init)."""
        if not self._temporal_window:
            return None
        recent = self._temporal_window[-3:]
        lines = []
        for ep in recent:
            lines.append(
                f"  - {ep['attack_type'] or 'clean'}: reward={ep['reward']:.3f}, "
                f"detected={ep['detected'] or 'no'}"
            )
        return "Recent episode history:\n" + "\n".join(lines)

    def _get_temporal_summary(self) -> str:
        """Summary of last N episodes for risk priming."""
        if not self._temporal_window:
            return "No prior episodes"
        return f"Last {len(self._temporal_window)} episodes: mean_reward={sum(e['reward'] for e in self._temporal_window)/len(self._temporal_window):.3f}"

    def _get_total_episodes(self) -> int:
        return len(self._temporal_window)

    def _build_scorecard(
        self, episode_id, attack_type, state, breakdown,
        guardian_detected_type, risk_history,
    ) -> Dict:
        return {
            "episode_id": episode_id,
            "worker_roles": ["finance"],
            "attack_type": attack_type or "clean",
            "attack_injection_step": next(
                (e["step"] for e in state.action_log if e.get("role") == "worker" and state.attack_active),
                -1
            ),
            "reward_components": breakdown.to_dict(),
            "reward_total": breakdown.total,
            "guardian_decisions": [
                {
                    "step": e["step"],
                    "risk_score": e.get("risk_score"),
                    "intervention": e.get("intervention"),
                    "reasoning": e.get("reasoning", "")[:100],
                }
                for e in state.action_log
                if e.get("role") == "guardian"
            ],
            "taint_report": self.env.get_taint_report(),
            "hash_chain_integrity": "MATCH" if self.env.verify_production_intact() else "MISMATCH",
            "compliance_simulator_mode": self.compliance_sim.mode,
            "canary_triggered": any(
                e.get("canary_fired") for e in state.action_log
            ),
            "risk_history": risk_history[-5:],
            "ucb_stats": self.ucb.get_stats(),
        }
