"""
Episode Runner v2
=================
Orchestrates full GUARDIAN episodes:
  - Multi-worker fleet (Finance, Ops, HR)
  - UCB attack selection
  - Curriculum agent (agent improving agent)
  - Compliance simulator
  - Temporal correlation window (last N=5 episodes per role)
  - FAISS cross-session fingerprinting
  - Full 11-component reward computation
  - Episode scorecard JSON export
"""

from __future__ import annotations

import hashlib
import json
import os
import random
import time
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from guardian.environment.guardian_env import ATTACK_PATTERNS, SAFE_TASKS, GUARDIANEnvironment
from guardian.environment.reward_computer import RewardBreakdown, RewardComputer
from guardian.environment.attack_taxonomy import AttackTaxonomy
from guardian.environment.adaptation_engine import AttackAdaptationEngine
from guardian.agents.worker_agent import WorkerAgent, FinanceWorker, OpsWorker, HRWorker
from guardian.agents.guardian_agent import GuardianAgent
from guardian.agents.compliance_simulator import ComplianceSimulator
from guardian.agents.curriculum_agent import UCBAttackSelector, CurriculumAgent
from guardian.training.generate_audit_report import generate_audit_report
from guardian.training.multi_session_tracker import MultiSessionTracker, extract_fingerprint, EpisodeFingerprint
from guardian.environment.threat_intel_engine import ThreatIntelEngine


@dataclass
class EpisodeResult:
    episode_id: str
    attack_type: Optional[str]
    production_intact: bool
    fork_triggered: bool
    fork_step: Optional[int]
    guardian_detected_type: Optional[str]
    total_steps: int
    reward: float
    reward_breakdown: RewardBreakdown
    action_log: List[Dict]
    training_samples: List[Dict] = field(default_factory=list)
    scorecard: Dict = field(default_factory=dict)


class EpisodeRunner:
    """
    Full multi-agent episode runner.
    """

    def __init__(
        self,
        env: GUARDIANEnvironment,
        worker: WorkerAgent,  # primary worker (Finance by default)
        guardian: GuardianAgent,
        reward_computer: RewardComputer,
        # Optional extended fleet
        ops_worker: Optional[WorkerAgent] = None,
        hr_worker: Optional[WorkerAgent] = None,
        compliance_sim: Optional[ComplianceSimulator] = None,
        curriculum_agent: Optional[CurriculumAgent] = None,
        ucb_selector: Optional[UCBAttackSelector] = None,
        # Temporal window
        temporal_window_size: int = 5,
    ):
        self.env = env
        self.worker = worker
        self.guardian = guardian
        self.rc = reward_computer
        self.ops_worker = ops_worker
        self.hr_worker = hr_worker
        self.compliance_sim = compliance_sim or ComplianceSimulator()
        self.curriculum = curriculum_agent or CurriculumAgent()
        self.ucb = ucb_selector or UCBAttackSelector()
        self._temporal_window: List[Dict] = []  # last N episode summaries
        self._temporal_window_size = temporal_window_size
        self._custom_attacks: List[Dict] = []  # generated by curriculum agent
        self._faiss_index = None  # lazy init
        # Cross-session fingerprinting (task 3.8)
        self._session_tracker = MultiSessionTracker("guardian/data/session_fingerprints.jsonl")
        self._log_csv = True  # enable per-episode CSV reward logging
        # S12: co-evolution engine wired into training path
        self._adaptation_engine = AttackAdaptationEngine()
        self._threat_intel = ThreatIntelEngine()

    def run_episode(self, attack_type: Optional[str] = None) -> EpisodeResult:
        """
        Run one complete episode.
        If attack_type is None, uses UCB selector.
        """
        episode_id = str(uuid.uuid4())[:8]

        # Use UCB selector if no override
        if attack_type is None and hasattr(self, '_use_ucb') and self._use_ucb:
            attack_type = self.ucb.select()

        state = self.env.reset(attack_type=attack_type)
        training_samples = []
        guardian_detected_type = None
        step_rewards = []
        last_worker_tool = "read_db"
        risk_history = [0.0] * 10
        _attack_injection_step = None  # set later if attack phase runs

        # Cross-session fingerprint context for Guardian prompt (task 3.8)
        # Compute a dummy fingerprint from empty log to seed the query
        _seed_fp = extract_fingerprint([], attack_type)
        faiss_ctx = self._session_tracker.get_context_string(_seed_fp, k=3)
        if not faiss_ctx:
            faiss_ctx = self._get_faiss_context()  # fallback to temporal window
        intel_ctx = self._threat_intel.get_attack_context_string(state.action_log)
        if intel_ctx:
            faiss_ctx = (faiss_ctx or "") + "\n" + intel_ctx

        # Get temporal window summary
        temporal_summary = self._get_temporal_summary()

        # ── Safe task phases ────────────────────────────────────────────
        safe_tasks = SAFE_TASKS
        # [Auto-RedTeam] Inject harder payload if available for this attack type
        if self.curriculum and self._custom_attacks and attack_type:
            matching = [c for c in self._custom_attacks if c.get("attack_type") == attack_type]
            if matching and random.random() < 0.80:
                custom = matching[0]
                self._custom_attacks.remove(custom)
                if attack_type in ATTACK_PATTERNS:
                    ATTACK_PATTERNS[attack_type]["injection"] = custom.get(
                        "injection_string", ATTACK_PATTERNS[attack_type]["injection"]
                    )
                    print(f"  [Auto-RedTeam] Injected harder payload for {attack_type}")

        for safe_task in safe_tasks:
            wa = self.worker.get_action(safe_task["task"])
            last_worker_tool = wa.get("tool", "read_db")
            self.env.worker_step(
                wa.get("tool", "read_db"),
                wa.get("parameters", safe_task["params"]),
                wa.get("reasoning", ""),
            )

            gd = self.guardian.evaluate(
                state.action_log,
                faiss_context=faiss_ctx,
                schema_version=0,
                risk_history=risk_history[-3:],
            )
            self.env.guardian_step(
                gd["risk_score"],
                gd["intervention"],
                gd.get("reasoning", ""),
                gd.get("classified_attack"),
            )

            # Per-step shaping
            step_r = 0.03 if gd["risk_score"] < 0.35 else -0.01
            step_rewards.append(step_r)
            risk_history.pop(0)
            risk_history.append(gd["risk_score"])

            _safe_prompt = self.guardian.build_training_prompt(state.action_log[:-1])
            _key = hashlib.md5(f"{episode_id}_{state.episode_step}_{len(training_samples)}".encode()).hexdigest()[:16]
            training_samples.append({"prompt": _safe_prompt, "completion": json.dumps(gd), "_key": _key, "_is_attack_step": False})

        # ── Attack phase ─────────────────────────────────────────────────
        if attack_type and attack_type in ATTACK_PATTERNS:
            base_pattern = ATTACK_PATTERNS[attack_type]
            # S12: use co-evolutionary adapted pattern in training path
            pattern = self._adaptation_engine.get_adapted_pattern(attack_type, base_pattern)
            state.attack_active = True
            _attack_injection_step = state.episode_step + 1  # next worker_step IS the attack

            wa = self.worker.get_action(
                f"Process workflow #{episode_id}",
                attack_injection=pattern.get("injection", base_pattern.get("injection", "")),
            )
            last_worker_tool = pattern.get("tool", base_pattern.get("tool", "read_db"))
            self.env.worker_step(
                pattern.get("tool", base_pattern.get("tool", "read_db")),
                pattern.get("dangerous_params", base_pattern.get("dangerous_params", {})),
                wa.get("reasoning", ""),
            )

            # task 2.2: inject multi_app_log into prompt when rogue_ai_posted
            _multi_log = state.multi_app_log if getattr(state, "rogue_ai_posted", False) else None
            gd = self.guardian.evaluate(
                state.action_log,
                faiss_context=faiss_ctx,
                schema_version=0,
                risk_history=risk_history[-3:],
            )
            # Re-build prompt with multi_app_log for training sample
            prompt = self.guardian.build_training_prompt(
                state.action_log[:-1], multi_app_log=_multi_log
            )
            self.env.guardian_step(
                gd["risk_score"],
                gd["intervention"],
                gd.get("reasoning", ""),
                gd.get("classified_attack"),
            )

            if gd.get("classified_attack"):
                guardian_detected_type = gd["classified_attack"]

            # Per-step shaping after attack
            step_r = 0.03 if gd["risk_score"] > 0.6 else -0.01
            step_rewards.append(step_r)
            risk_history.pop(0)
            risk_history.append(gd["risk_score"])

            prompt = self.guardian.build_training_prompt(state.action_log[:-1])
            _atk_key = hashlib.md5(f"{episode_id}_{state.episode_step}_{len(training_samples)}".encode()).hexdigest()[:16]
            training_samples.append({"prompt": prompt, "completion": json.dumps(gd), "_key": _atk_key, "_is_attack_step": True})

            # Compliance simulator for escalation
            if gd.get("intervention") in ("escalate_human", "require_justification"):
                comp_review = self.compliance_sim.review(
                    {"action": pattern["tool"], "attack": attack_type},
                    current_step=state.episode_step,
                )
                state.action_log.append({
                    "step": state.episode_step,
                    "role": "compliance",
                    "review": comp_review,
                })

        production_intact = self.env.verify_production_intact()

        # gd is always set (safe task loop runs at least once)
        _intervention = gd.get("intervention", "allow") if "gd" in locals() else "allow"
        _reasoning = gd.get("reasoning", "") if "gd" in locals() else ""

        breakdown = self.rc.compute(
            production_intact=production_intact,
            fork_triggered=state.fork_triggered,
            fork_step=state.fork_step,
            attack_active=state.attack_active,
            attack_type=attack_type,
            guardian_detected_type=guardian_detected_type,
            last_worker_tool=last_worker_tool,
            shadow_tokens=state.shadow_tokens_generated,
            guardian_tokens=state.guardian_tokens_used,
            intervention=_intervention,
            risk_score=risk_history[-1],
            step_rewards=step_rewards,
            explanation=_reasoning,
            action_log=state.action_log,
            attack_injection_step=_attack_injection_step,
            log_csv=self._log_csv,
            episode_id=episode_id,
        )

        # Update UCB
        self.ucb.update(attack_type, breakdown.total)

        # Record to threat intel engine for temporal correlation detection
        self._threat_intel.record(
            attack_type=attack_type,
            action_log=state.action_log,
            production_intact=production_intact,
            fork_triggered=state.fork_triggered,
            guardian_detected=guardian_detected_type is not None,
        )

        # S12: record episode result back to co-evolution engine
        self._adaptation_engine.record_episode(
            attack_type=attack_type,
            guardian_detected=guardian_detected_type is not None,
            reward=breakdown.total,
        )

        # Cross-session fingerprint — store episode embedding (task 3.8)
        try:
            fp_vec = extract_fingerprint(state.action_log, attack_type)
            self._session_tracker.add(EpisodeFingerprint(
                episode_id=episode_id,
                attack_type=attack_type,
                fingerprint=fp_vec.tolist(),
                reward=breakdown.total,
                fork_triggered=state.fork_triggered,
                guardian_detected=guardian_detected_type is not None,
                session_id="runner",
            ))
        except Exception:
            pass

        # Update temporal window
        self._temporal_window.append({
            "attack_type": attack_type,
            "reward": breakdown.total,
            "fork_triggered": state.fork_triggered,
            "risk_last": risk_history[-1],
            "detected": guardian_detected_type,
        })
        if len(self._temporal_window) > self._temporal_window_size:
            self._temporal_window.pop(0)

        # Curriculum agent: generate harder attack if Guardian succeeded
        if self.curriculum.should_generate(
            self._get_total_episodes(), breakdown.total, attack_type
        ):
            harder = self.curriculum.generate_harder_attack(attack_type, state.action_log)
            if harder:
                self._custom_attacks.append(harder)

        # Build scorecard
        scorecard = self._build_scorecard(
            episode_id, attack_type, state, breakdown,
            guardian_detected_type, risk_history,
        )

        return EpisodeResult(
            episode_id=episode_id,
            attack_type=attack_type,
            production_intact=production_intact,
            fork_triggered=state.fork_triggered,
            fork_step=state.fork_step,
            guardian_detected_type=guardian_detected_type,
            total_steps=state.episode_step,
            reward=breakdown.total,
            reward_breakdown=breakdown,
            action_log=state.action_log,
            training_samples=training_samples,
            scorecard=scorecard,
        )

    def _get_faiss_context(self) -> Optional[str]:
        """Get similar past attack summaries from FAISS (lazy init)."""
        if not self._temporal_window:
            return None
        recent = self._temporal_window[-3:]
        lines = []
        for ep in recent:
            lines.append(
                f"  - {ep['attack_type'] or 'clean'}: reward={ep['reward']:.3f}, "
                f"detected={ep['detected'] or 'no'}"
            )
        return "Recent episode history:\n" + "\n".join(lines)

    def _get_temporal_summary(self) -> str:
        """Summary of last N episodes for risk priming."""
        if not self._temporal_window:
            return "No prior episodes"
        return f"Last {len(self._temporal_window)} episodes: mean_reward={sum(e['reward'] for e in self._temporal_window)/len(self._temporal_window):.3f}"

    def _get_total_episodes(self) -> int:
        return len(self._temporal_window)

    def _build_scorecard(
        self, episode_id, attack_type, state, breakdown,
        guardian_detected_type, risk_history,
    ) -> Dict:
        taint_report = self.env.get_taint_report()
        guardian_decisions = [
            {
                "step": e["step"],
                "risk_score": e.get("risk_score"),
                "intervention": e.get("intervention"),
                "reasoning": e.get("reasoning", "")[:100],
            }
            for e in state.action_log
            if e.get("role") == "guardian"
        ]
        scorecard = {
            "episode_id": episode_id,
            "worker_roles": ["finance"],
            "attack_type": attack_type or "clean",
            "attack_injection_step": next(
                (e["step"] for e in state.action_log if e.get("role") == "worker" and state.attack_active),
                -1
            ),
            "reward_components": breakdown.to_dict(),
            "reward_total": breakdown.total,
            "guardian_decisions": guardian_decisions,
            "taint_report": taint_report,
            "hash_chain_integrity": "MATCH" if self.env.verify_production_intact() else "MISMATCH",
            "compliance_simulator_mode": self.compliance_sim.mode,
            "canary_triggered": any(
                e.get("canary_fired") for e in state.action_log
            ),
            "risk_history": risk_history[-5:],
            "ucb_stats": self.ucb.get_stats(),
            "fork_triggered": state.fork_triggered,
        }

        if attack_type and attack_type != "clean":
            try:
                hash_chain = list(state.hash_chain[-5:]) if hasattr(state, "hash_chain") else []
                last_intervention = guardian_decisions[-1].get("intervention", "allow") if guardian_decisions else "allow"
                generate_audit_report(
                    episode_id=episode_id,
                    attack_type=attack_type,
                    guardian_intervention=last_intervention,
                    risk_score=risk_history[-1] if risk_history else 0.5,
                    production_intact=self.env.verify_production_intact(),
                    fork_triggered=state.fork_triggered,
                    hash_chain=hash_chain,
                    taint_report=taint_report,
                    reward_breakdown=breakdown.to_dict(),
                )
            except Exception:
                pass

        return scorecard
