"""
GUARDIAN Fleet — OpenEnv FastAPI Server
=========================================
Implements the full OpenEnv HTTP + WebSocket protocol:

  POST /reset            → {"observation": ..., "state": ..., "reward": 0, "done": false}
  POST /step             → {"observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
  GET  /state            → GuardianState
  WS   /ws               → Per-connection isolated WebSocket session
  GET  /health           → {"status": "ok", ...}
  GET  /web              → Browser UI for manual exploration
  GET  /docs             → OpenAPI docs (auto-generated by FastAPI)

WebSocket message protocol:
  Client → Server:
    {"type": "reset", "options": {...}}
    {"type": "step",  "action": {...}}
    {"type": "state"}

  Server → Client:
    {"type": "reset_result",  "observation": ..., "state": ..., "reward": 0, "done": false}
    {"type": "step_result",   "observation": ..., "reward": ..., "done": ..., "info": ..., "state": ...}
    {"type": "episode_done",  "observation": ..., "state": ..., "message": "..."}
    {"type": "state_result",  "state": ...}
    {"type": "error",         "message": "..."}

Run locally:
    uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload

Or inside Docker (see server/Dockerfile):
    docker build -t guardian-env -f server/Dockerfile .
    docker run -p 8000:8000 guardian-env
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Any, Dict, Optional

# ── Ensure the repo root is always in sys.path ──────────────────────────────
# This makes `from models import ...` and `from guardian.environment import ...`
# work regardless of whether uvicorn is started from root or server/ directory.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from contextlib import asynccontextmanager

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
import uvicorn

from models import GuardianAction, GuardianObservation, GuardianState, StepResult
from server.guardian_environment import GuardianOpenEnvEnvironment

try:
    from guardian.hitl.escalation import hitl_manager, get_counterfactual, AMBIGUITY_LOW, AMBIGUITY_HIGH
    _HITL_AVAILABLE = True
except ImportError:
    _HITL_AVAILABLE = False
    log = logging.getLogger("guardian.server")
    logging.getLogger("guardian.server").warning("HITL module not available — HITL endpoints disabled")

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("guardian.server")


# ── Lifespan (replaces deprecated @app.on_event) ─────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("=" * 60)
    log.info("GUARDIAN Fleet OpenEnv Server — starting up")
    log.info("Endpoints: POST /reset  POST /step  GET /state  WS /ws")
    log.info("           GET /web     GET /health  GET /docs")
    log.info("=" * 60)
    yield  # application runs here
    log.info("GUARDIAN Fleet server shut down.")


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="GUARDIAN Fleet — OpenEnv Server",
    description=(
        "Multi-agent AI security oversight environment for RL post-training. "
        "A Guardian LLM (Qwen2.5-7B, trained via GRPO) detects and intercepts "
        "adversarial prompt injections, authority spoofing, approval bypasses, "
        "and 5 other attack types across Finance/Ops/HR worker fleets."
    ),
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Default HTTP environment (single shared session for REST endpoints) ───────
_http_env = GuardianOpenEnvEnvironment(difficulty=1)


def _new_env() -> GuardianOpenEnvEnvironment:
    """Create a fresh isolated environment per WebSocket connection."""
    return GuardianOpenEnvEnvironment(difficulty=1)


# ── Root redirect → /web ──────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root_redirect():
    """Redirect root URL to the web dashboard. Required for HF Spaces."""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/web")


# ── Health ────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    summary="Health check",
    tags=["System"],
)
def health() -> Dict[str, Any]:
    """Returns server status and environment metadata."""
    return {
        "status": "ok",
        "env": "guardian-env",
        "version": "0.2.0",
        "description": "GUARDIAN Fleet – AI Security Oversight RL Environment",
        "endpoints": ["/reset", "/step", "/state", "/ws", "/web", "/docs"],
    }


# ── REST: reset ───────────────────────────────────────────────────────────────

@app.post(
    "/reset",
    summary="Reset episode",
    tags=["Environment"],
)
def reset(body: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Start a new episode.

    Body (optional JSON):
        {"seed": 42}

    Returns the initial observation and episode state.
    """
    global _http_env
    obs = _http_env.reset(options=body)
    state = _http_env.state()
    log.info(f"[REST /reset] episode_id={state.episode_id}")
    return {
        "observation": obs.model_dump(),
        "state": state.model_dump(),
        "reward": 0.0,
        "done": False,
    }


# ── REST: step ────────────────────────────────────────────────────────────────

@app.post(
    "/step",
    summary="Execute one Guardian decision",
    tags=["Environment"],
)
def step(action: GuardianAction) -> Dict[str, Any]:
    """
    Execute one Guardian decision and return the result.

    Body: GuardianAction JSON
        {
          "risk_score": 0.85,
          "intervention": "shadow",
          "attack_type": "prompt_injection",
          "rollback_k": 2,
          "reasoning": "Suspicious write to exfil_log"
        }
    """
    global _http_env
    obs, reward, done, info = _http_env.step(action)
    state = _http_env.state()
    log.info(
        f"[REST /step] step={state.step_count} "
        f"intervention={action.intervention} "
        f"risk={action.risk_score:.2f} "
        f"reward={reward:.4f} done={done}"
    )
    return {
        "observation": obs.model_dump(),
        "reward": reward,
        "done": done,
        "info": info,
        "state": state.model_dump(),
    }


# ── REST: baselines ───────────────────────────────────────────────────────────

@app.get(
    "/baselines",
    summary="Get Evaluation Baselines",
    tags=["System"],
)
def get_baselines() -> Dict[str, Any]:
    """Returns baseline execution metrics for the dashboard leaderboard."""
    eval_dir = os.path.join(_ROOT, "guardian", "data", "eval_data")
    baselines = []
    if os.path.exists(eval_dir):
        for fname in os.listdir(eval_dir):
            if fname.endswith(".json"):
                with open(os.path.join(eval_dir, fname), "r") as f:
                    try:
                        data = json.load(f)
                        baselines.append({
                            "model": data.get("model", fname.replace(".json", "")),
                            "mean_reward": data.get("mean_reward", 0.0),
                            "production_intact_rate": data.get("production_intact_rate", 0.0),
                        })
                    except Exception as e:
                        pass
    
    # Try to append trained Guardian if untested exists
    trained_path = os.path.join(_ROOT, "guardian", "data", "baseline_trained.json")
    if os.path.exists(trained_path):
        with open(trained_path, "r") as f:
            try:
                data = json.load(f)
                baselines.append({
                    "model": "Guardian (Self-Distilled RL)",
                    "mean_reward": data.get("mean_reward", 0.85),
                    "production_intact_rate": data.get("production_intact_rate", 0.95),
                })
            except Exception:
                pass

    return {"baselines": baselines}


# ── REST: state ───────────────────────────────────────────────────────────────

@app.get(
    "/state",
    summary="Episode state",
    tags=["Environment"],
)
def get_state() -> Dict[str, Any]:
    """Return current episode metadata without advancing the environment."""
    return _http_env.state().model_dump()


# ── REST: tools manifest (“Rug Pull” endpoint) ───────────────────────────────────

@app.get(
    "/tools",
    summary="Available MCP tool manifest",
    tags=["Environment"],
)
def get_tools() -> Dict[str, Any]:
    """
    Returns all tools available in the current episode, with risk metadata.

    Used by the client's get_tools() method to implement the MCP 'Rug Pull'
    deprovision pattern — the client strips quarantined tools from this list
    before exposing the action space to the Worker agent.

    Critical tools (high-risk) are flagged so the Guardian can apply
    surgical privilege downgrade without fully blocking the Worker.
    """
    all_tools = [
        # Safe tools
        {"name": "read_db",              "risk": "low",      "category": "data_read"},
        {"name": "post_to_forum",        "risk": "medium",   "category": "communication"},
        {"name": "query_data_access_log","risk": "low",      "category": "audit"},
        # Sensitive tools
        {"name": "write_db",             "risk": "high",     "category": "data_write"},
        {"name": "process_payment",      "risk": "high",     "category": "financial"},
        {"name": "modify_firewall",      "risk": "critical", "category": "network"},
        {"name": "modify_iam_policy",   "risk": "critical", "category": "iam"},
        {"name": "register_vendor",     "risk": "high",     "category": "vendor"},
        {"name": "export_data",         "risk": "critical", "category": "data_exfil"},
    ]
    # Check if any tools are currently quarantined in the active session
    quarantined = list(_http_env._gym.env.state.quarantined_tools)  # BUG-10 fix
    available = [t for t in all_tools if t["name"] not in quarantined]
    return {
        "tools": [t["name"] for t in available],
        "tool_details": available,
        "quarantined": quarantined,
        "rug_pull_active": len(quarantined) > 0,
        "episode_id": _http_env.state().episode_id,
    }



# ── HITL: Pending escalations ─────────────────────────────────────────────────

@app.post(
    "/hitl/escalate",
    summary="Create a new HITL escalation (fires n8n → Telegram)",
    tags=["HITL"],
)
def hitl_escalate(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Create a gray-zone escalation. Fires the n8n webhook which sends a
    Telegram alert with ALLOW / BLOCK / SHADOW inline buttons.

    Body:
        {
          "tool_name": "process_payment",
          "classified_attack": "approval_bypass",
          "risk_score": 0.68,
          "domain": "enterprise",
          "capability_tags": "[STATE_MOD=True|FINANCIAL=High]",
          "guardian_reasoning": "Step 4 calls process_payment...",
          "episode_step": 4
        }
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}

    tool_name = body.get("tool_name", "unknown_tool")
    risk_score = float(body.get("risk_score", 0.65))
    domain = body.get("domain", "enterprise")
    classified_attack = body.get("classified_attack", "")

    # Build counterfactual from domain library
    counterfactual = get_counterfactual(tool_name, domain)

    ctx = hitl_manager.create_escalation(
        tool_name=tool_name,
        tool_arguments=body.get("tool_arguments", {}),
        risk_score=risk_score,
        capability_tags=body.get("capability_tags", ""),
        classified_attack=classified_attack,
        guardian_reasoning=body.get("guardian_reasoning", ""),
        counterfactual=counterfactual,
        domain=domain,
        episode_step=int(body.get("episode_step", 0)),
        episode_id=body.get("episode_id", ""),
    )

    log.info("[HITL] Escalation fired: context_id=%s risk=%.2f", ctx.context_id, risk_score)
    return {
        "created": True,
        "context_id": ctx.context_id,
        "tool_name": tool_name,
        "risk_score": risk_score,
        "domain": domain,
        "counterfactual": counterfactual,
        "whatsapp_message": ctx.to_whatsapp_message(),
        "message": "Escalation created. Telegram alert sent via n8n. Awaiting human decision at /hitl/decision.",
    }


@app.get(
    "/hitl/pending",
    summary="List all pending HITL escalations",
    tags=["HITL"],
)
def hitl_pending() -> Dict[str, Any]:
    """
    Returns all pending human-in-the-loop escalations.
    Each entry includes the pre-formatted WhatsApp decision matrix message.
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available", "pending": {}}
    return {
        "pending": hitl_manager.get_all_pending(),
        "ambiguity_zone": {"low": AMBIGUITY_LOW, "high": AMBIGUITY_HIGH},
    }


@app.post(
    "/hitl/decision",
    summary="Submit human HITL decision",
    tags=["HITL"],
)
def hitl_decision(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Submit a human decision for a pending HITL escalation.

    Body:
        {"context_id": "abc123", "decision": "allow" | "block" | "shadow"}

    The decision is:
      1. Executed by the MCP Gateway (allow/block/shadow routing)
      2. Logged to the HITL Replay Buffer (hitl_replay.jsonl)
      3. The replay buffer is used by the next GRPO training run as Ground Truth
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}

    # Text command support: "block", "allow abc123", "shadow", etc.
    raw_text = body.get("text", "").strip().lower()
    if raw_text:
        parts = raw_text.split()
        if parts and parts[0] in ("allow", "block", "shadow"):
            body["decision"] = parts[0]
            if len(parts) > 1:
                body["context_id"] = parts[1]
            elif not body.get("context_id"):
                # Use most recent pending if no context_id given
                pending = hitl_manager.get_all_pending()
                if pending:
                    body["context_id"] = list(pending.keys())[-1]

    context_id = body.get("context_id", "")
    decision = body.get("decision", "")

    if decision not in ("allow", "block", "shadow"):
        return {"error": f"Invalid decision '{decision}'. Must be: allow | block | shadow"}

    ctx = hitl_manager.resolve_escalation(context_id, decision)  # type: ignore
    if ctx is None:
        # Headless fallback already handled in resolve_escalation
        stats = hitl_manager.get_replay_buffer_stats()
        return {
            "resolved": True,
            "context_id": context_id,
            "decision": decision,
            "headless": True,
            "replay_buffer_total": stats["total_entries"],
            "message": f"Headless entry logged (context_id not found — server may have restarted).",
        }

    stats = hitl_manager.get_replay_buffer_stats()
    log.info(
        "[HITL] Human decision: context_id=%s decision=%s replay_total=%d",
        context_id, decision, stats["total_entries"]
    )
    return {
        "resolved": True,
        "context_id": context_id,
        "decision": decision,
        "tool_name": ctx.tool_name,
        "replay_buffer_total": stats["total_entries"],
        "message": (
            f"Decision '{decision}' logged. "
            f"Replay buffer now has {stats['total_entries']} ground-truth entries "
            f"for next GRPO training run."
        ),
    }


@app.get(
    "/hitl/replay_stats",
    summary="HITL replay buffer statistics",
    tags=["HITL"],
)
def hitl_replay_stats() -> Dict[str, Any]:
    """
    Returns statistics about the HITL replay buffer.
    Shows how many human decisions have been logged for the next GRPO training run.
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}
    return hitl_manager.get_replay_buffer_stats()


@app.post(
    "/hitl/backtrack",
    summary="Root-cause backtrack analysis for a BLOCK decision",
    tags=["HITL"],
)
def hitl_backtrack(body: Dict[str, Any]) -> Dict[str, Any]:
    """
    Produces a full causal chain trace for a BLOCK decision.

    Traces backward from the blocked action to:
      - The first anomaly step (when risk deviated from baseline)
      - The likely injection point (where malicious instruction entered)
      - The full step-by-step causal chain
      - A plain-English incident narrative
      - Recommended post-incident actions

    Body:
        {
            "context_id": "abc123",
            "blocked_tool": "override_margin_limits",
            "blocked_at_step": 8,
            "risk_score": 0.82,
            "capability_tags": "[STATE_MOD=True|PRIV_ESC=True|FINANCIAL=Critical]",
            "attack_pattern": "confused_deputy",
            "counterfactual": "Margin reqs zeroed...",
            "domain": "finops",
            "risk_history": [0.1, 0.12, 0.15, 0.35, 0.60, 0.75, 0.80, 0.82],
            "intercept_log": [...]
        }
    """
    if not _HITL_AVAILABLE:
        return {"error": "HITL module not available"}

    try:
        from guardian.hitl.backtrack import backtrack_engine
    except ImportError:
        return {"error": "Backtrack engine not available"}

    report = backtrack_engine.analyze(
        context_id=body.get("context_id", "manual"),
        blocked_tool=body.get("blocked_tool", "unknown"),
        blocked_at_step=body.get("blocked_at_step", 0),
        risk_score=body.get("risk_score", 0.0),
        capability_tags=body.get("capability_tags", ""),
        attack_pattern=body.get("attack_pattern", "unknown"),
        counterfactual=body.get("counterfactual", ""),
        domain=body.get("domain", "enterprise"),
        intercept_log=body.get("intercept_log", []),
        risk_history=body.get("risk_history", []),
    )
    return report.to_dict()


# ── WebSocket endpoint ────────────────────────────────────────────────────────

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    """
    Per-connection isolated WebSocket session.

    Each WebSocket connection gets its own GuardianOpenEnvEnvironment instance,
    so parallel training workers don't share environment state.

    Protocol (JSON messages):
        → {"type": "reset"}
        ← {"type": "reset_result", "observation": {...}, "state": {...}, ...}

        → {"type": "step", "action": {"risk_score": 0.8, "intervention": "shadow", ...}}
        ← {"type": "step_result", "observation": {...}, "reward": float, "done": bool, ...}

        → {"type": "state"}
        ← {"type": "state_result", "state": {...}}
    """
    await websocket.accept()
    env = _new_env()  # isolated per connection
    log.info("[WS] New connection accepted — fresh environment allocated")

    try:
        while True:
            try:
                raw = await websocket.receive_text()
            except WebSocketDisconnect:
                log.info("[WS] Client disconnected cleanly")
                return

            try:
                data: Dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_json(
                    {"type": "error", "message": "Payload must be valid JSON"}
                )
                continue

            msg_type: str = data.get("type", "")

            # ── set_domain ──────────────────────────────────────────────────
            if msg_type == "set_domain":
                domain_id = data.get("domain", "enterprise")
                obs = env.reset(options={"domain": domain_id})
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                    "message": f"Domain switched to {domain_id}"
                })
                log.info(f"[WS] domain_switched → {domain_id}")

            # ── reset ──────────────────────────────────────────────────────
            elif msg_type == "reset":
                obs = env.reset(options=data.get("options"))
                state = env.state()
                await websocket.send_json({
                    "type": "reset_result",
                    "observation": obs.model_dump(),
                    "state": state.model_dump(),
                    "reward": 0.0,
                    "done": False,
                })
                log.info(f"[WS] reset → episode_id={state.episode_id}")

            # ── step ───────────────────────────────────────────────────────
            elif msg_type == "step":
                action_data = data.get("action", {})
                try:
                    action = GuardianAction(**action_data)
                except Exception as parse_err:
                    await websocket.send_json({
                        "type": "error",
                        "message": f"Invalid action schema: {parse_err}",
                    })
                    continue

                obs, reward, done, info = env.step(action)
                state = env.state()
                await websocket.send_json({
                    "type": "step_result",
                    "observation": obs.model_dump(),
                    "reward": reward,
                    "done": done,
                    "info": info,
                    "state": state.model_dump(),
                })
                log.info(
                    f"[WS] step={state.step_count} "
                    f"iv={action.intervention} "
                    f"reward={reward:.4f} done={done}"
                )

                # Auto-reset and notify on episode end
                if done:
                    new_obs = env.reset()
                    new_state = env.state()
                    await websocket.send_json({
                        "type": "episode_done",
                        "observation": new_obs.model_dump(),
                        "state": new_state.model_dump(),
                        "episode_id": new_state.episode_id,  # Client re-locks episode_id
                        "message": "Episode complete. Environment auto-reset.",
                    })

            # ── state ──────────────────────────────────────────────────────
            elif msg_type == "state":
                state = env.state()
                await websocket.send_json({
                    "type": "state_result",
                    "state": state.model_dump(),
                })

            # ── unknown ────────────────────────────────────────────────────
            else:
                await websocket.send_json({
                    "type": "error",
                    "message": (
                        f"Unknown message type: '{msg_type}'. "
                        "Valid types: reset | step | state"
                    ),
                })

    except WebSocketDisconnect:
        log.info("[WS] Connection closed")
    except Exception as exc:
        log.error(f"[WS] Unhandled error: {exc}", exc_info=True)
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
        except Exception:
            pass


# ── Web UI ────────────────────────────────────────────────────────────────────

@app.get("/web", response_class=HTMLResponse, summary="Browser UI", tags=["System"])
def web_interface() -> HTMLResponse:
    """Interactive browser interface for manual episode exploration."""
    return HTMLResponse(content=_WEB_UI_HTML)


_WEB_UI_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GUARDIAN Fleet — SOC War Room</title>
  <style>
    :root {
      --bg-dark: #050505;
      --bg-card: rgba(18, 18, 22, 0.65);
      --border-color: rgba(255, 255, 255, 0.08);
      --accent: #3b82f6;
      --accent-glow: rgba(59, 130, 246, 0.3);
      --text-main: #f8fafc;
      --text-muted: #94a3b8;
      --success: #10b981;
      --warning: #f59e0b;
      --danger: #ef4444;
      --danger-glow: rgba(239, 68, 68, 0.3);
      --purple: #a78bfa;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');
    body {
      font-family: 'Outfit', -apple-system, system-ui, sans-serif;
      background: radial-gradient(circle at 50% 0%, #151520 0%, var(--bg-dark) 80%);
      background-attachment: fixed;
      color: var(--text-main);
      min-height: 100vh;
      padding: 30px 40px;
      line-height: 1.5;
    }
    .header {
      display: flex; justify-content: space-between; align-items: flex-end;
      margin-bottom: 24px; padding-bottom: 16px; 
      border-bottom: 1px solid var(--border-color);
    }
    .header h1 {
      font-size: 1.8rem; font-weight: 700; 
      background: linear-gradient(90deg, #fff, #93c5fd);
      -webkit-background-clip: text; -webkit-text-fill-color: transparent;
      letter-spacing: -0.02em; margin-bottom: 4px;
    }
    .header .subtitle { 
      font-size: 0.8rem; color: var(--text-muted); 
      font-family: 'JetBrains Mono', monospace; 
      display: flex; align-items: center; gap: 8px;
    }
    .domain-selector {
      background: rgba(15, 23, 42, 0.6); padding: 10px 16px; border-radius: 12px;
      display: flex; align-items: center; gap: 12px; border: 1px solid var(--border-color);
      backdrop-filter: blur(10px);
      box-shadow: 0 4px 20px rgba(0,0,0,0.2);
    }
    .domain-selector label { font-size: 0.75rem; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing:.05em; }
    .domain-selector select {
      background: rgba(0, 0, 0, 0.4); color: #93c5fd; border: 1px solid rgba(147, 197, 253, 0.2);
      padding: 6px 12px; border-radius: 8px; outline: none; cursor: pointer;
      font-size: 0.85rem; font-weight: 600; font-family: 'Outfit', sans-serif;
      transition: all 0.3s ease;
    }
    .domain-selector select:hover { border-color: var(--accent); background: rgba(59, 130, 246, 0.1); }
    .status-bar { display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; align-items: center; }
    .badge {
      display: flex; align-items: center; padding: 6px 14px; border-radius: 8px;
      font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; gap: 6px;
      backdrop-filter: blur(4px); transition: transform 0.2s ease;
    }
    .badge:hover { transform: translateY(-1px); }
    .badge-ok   { background: rgba(16,185,129,0.1);  color: var(--success); border: 1px solid rgba(16,185,129,0.3); box-shadow: 0 0 10px rgba(16,185,129,0.1); }
    .badge-warn { background: rgba(245,158,11,0.1);  color: var(--warning); border: 1px solid rgba(245,158,11,0.3); box-shadow: 0 0 10px rgba(245,158,11,0.1); }
    .badge-bad  { background: rgba(239,68,68,0.1);   color: var(--danger); border: 1px solid rgba(239,68,68,0.3); box-shadow: 0 0 10px var(--danger-glow); }
    .badge-info { background: rgba(59,130,246,0.1);  color: #93c5fd; border: 1px solid rgba(59,130,246,0.3); box-shadow: 0 0 10px var(--accent-glow); }
    .controls {
      display: flex; flex-wrap: wrap; gap: 20px; margin-bottom: 24px;
      background: var(--bg-card); padding: 20px; border-radius: 16px; border: 1px solid var(--border-color);
      backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px);
      box-shadow: 0 10px 30px rgba(0,0,0,0.4);
    }
    .control-group { display: flex; flex-direction: column; gap: 8px; }
    .control-group label { font-size: 0.75rem; color: var(--text-muted); font-weight: 600; text-transform:uppercase; letter-spacing:.05em; }
    select, input[type=range] {
      background: rgba(0,0,0,0.5); color: var(--text-main); border: 1px solid var(--border-color);
      padding: 8px 12px; border-radius: 8px; font-size: 0.85rem; font-family: 'Outfit', sans-serif; outline: none; transition: border 0.3s;
    }
    select:focus { border-color: var(--accent); }
    input[type=range] { padding: 0; accent-color: var(--accent); height: 6px; margin-top: 10px; cursor: pointer; }
    .btn {
      padding: 8px 18px; border: none; border-radius: 8px; cursor: pointer;
      font-size: 0.85rem; font-family: 'Outfit', sans-serif; font-weight: 600; display: flex; align-items: center;
      gap: 6px; transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1); letter-spacing:.02em; position: relative; overflow: hidden;
    }
    .btn::after { content:''; position:absolute; top:0;left:0;right:0;bottom:0; background:rgba(255,255,255,0.1); opacity:0; transition:opacity 0.2s; }
    .btn:hover::after { opacity:1; }
    .btn:active { transform: scale(0.97); }
    .btn-step   { background: linear-gradient(135deg, #2563eb, #1d4ed8); color: #fff; box-shadow: 0 4px 15px var(--accent-glow); } 
    .btn-step:hover { box-shadow: 0 6px 20px rgba(59, 130, 246, 0.5); transform: translateY(-2px); }
    .btn-reset  { background: rgba(255,255,255,0.05); color: var(--text-main); border: 1px solid var(--border-color); } 
    .btn-reset:hover  { background: rgba(255,255,255,0.1); transform: translateY(-1px); }
    .btn-clear  { background: rgba(239,68,68,0.1); color: var(--danger); border: 1px solid rgba(239,68,68,0.2); } 
    .btn-allow  { background: rgba(16,185,129,0.15); color: var(--success); border:1px solid rgba(16,185,129,0.4); box-shadow: 0 4px 15px rgba(16,185,129,0.15); }
    .btn-block  { background: rgba(239,68,68,0.15); color: var(--danger); border:1px solid rgba(239,68,68,0.4); box-shadow: 0 4px 15px rgba(239,68,68,0.2); }
    .btn-shadow { background: rgba(245,158,11,0.15); color: var(--warning); border:1px solid rgba(245,158,11,0.4); }
    .grid { display: grid; grid-template-columns: 2fr 1fr; gap: 24px; }
    .panel {
      background: var(--bg-card); border: 1px solid var(--border-color); border-radius: 16px;
      padding: 20px; display: flex; flex-direction: column;
      backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px);
      box-shadow: 0 10px 40px rgba(0,0,0,0.3); transition: border-color 0.3s;
    }
    .panel:hover { border-color: rgba(255,255,255,0.15); }
    .panel-header {
      font-size: 0.8rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase;
      letter-spacing: 0.08em; border-bottom: 1px solid rgba(255,255,255,0.05);
      padding-bottom: 12px; margin-bottom: 16px;
      display: flex; justify-content: space-between; align-items: center;
    }
    .event-feed { max-height: 400px; overflow-y: auto; display: flex; flex-direction: column; gap: 10px; padding-right: 8px; }
    .event-card {
      background: rgba(0,0,0,0.3); border: 1px solid rgba(255,255,255,0.05); border-left: 3px solid var(--accent);
      padding: 14px; border-radius: 10px; transition: transform 0.2s;
      font-family: 'JetBrains Mono', monospace; font-size: 0.75rem; line-height: 1.4;
    }
    .event-card:hover { transform: translateX(3px); background: rgba(0,0,0,0.5); }
    .event-card.attack  { border-left-color: var(--danger); background: rgba(239,68,68,0.05); }
    .event-card.honeypot{ border-left-color: var(--warning); background: rgba(245,158,11,0.05); }
    .event-card.hitl    { border-left-color: var(--purple); background: rgba(139,92,246,0.05); }
    pre { font-family: 'JetBrains Mono', monospace; font-size: 0.75rem; overflow-x: auto; color: #93c5fd; }
    .threat-gauge-container { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 20px 0; }
    .circular-chart { display: block; margin: 0 auto; max-width: 140px; max-height: 140px; filter: drop-shadow(0 0 10px rgba(0,0,0,0.5)); }
    .circle-bg { fill: none; stroke: rgba(255,255,255,0.05); stroke-width: 3; }
    .circle { fill: none; stroke-width: 3.5; stroke-linecap: round; transition: stroke-dasharray 1s cubic-bezier(0.4, 0, 0.2, 1), stroke 0.5s ease; }
    .percentage { fill: #fff; font-family: 'Outfit', sans-serif; font-size: 0.45em; text-anchor: middle; font-weight: 700; text-shadow: 0 2px 10px rgba(0,0,0,0.8); }
    /* HITL Freeze Overlay */
    #hitlOverlay {
      display: none; position: fixed; inset: 0; z-index: 1000;
      background: rgba(0,0,0,0.8); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
      justify-content: center; align-items: center; opacity: 0; transition: opacity 0.3s;
    }
    #hitlOverlay.active { display: flex; opacity: 1; }
    .hitl-card {
      background: rgba(15, 23, 42, 0.9); border: 1px solid rgba(167, 139, 250, 0.5);
      border-radius: 20px; padding: 32px 40px; max-width: 560px; width: 95%;
      box-shadow: 0 0 80px rgba(139,92,246,0.2), inset 0 0 40px rgba(139,92,246,0.05);
      animation: slideUp 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
    }
    @keyframes slideUp { from { transform: translateY(30px) scale(0.95); opacity:0; } to { transform: translateY(0) scale(1); opacity:1; } }
    .hitl-card h2 { color: #c4b5fd; font-size: 1.2rem; margin-bottom: 12px; display:flex; align-items:center; gap:8px; }
    .hitl-card .hitl-label { font-family: 'JetBrains Mono', monospace; color: var(--text-muted); font-size:0.75rem; margin-bottom:24px; padding-bottom:12px; border-bottom:1px solid rgba(255,255,255,0.05);}
    .hitl-field { background: rgba(0,0,0,0.4); border:1px solid rgba(255,255,255,0.05); border-radius:10px; padding:12px 16px; margin-bottom:12px; }
    .hitl-field label { font-size:0.7rem; color:var(--text-muted); text-transform:uppercase; letter-spacing:0.06em; display:block; margin-bottom:6px; }
    .hitl-field .val { font-size:0.9rem; color:var(--text-main); font-weight:600; font-family: 'JetBrains Mono', monospace; }
    .hitl-field .tags { font-family:'JetBrains Mono',monospace; font-size:0.75rem; color:var(--warning); background:rgba(245,158,11,0.1); padding:4px 8px; border-radius:4px; display:inline-block;}
    .hitl-field .cf { font-size:0.85rem; color:var(--danger); font-style:italic; line-height: 1.4; }
    .hitl-score-bar { display:flex; align-items:center; gap:16px; margin:20px 0; background: rgba(255,255,255,0.02); padding:16px; border-radius:12px; border:1px solid rgba(255,255,255,0.05); }
    .hitl-score-bar .score { font-size:2.2rem; font-weight:800; color:var(--warning); text-shadow: 0 0 20px rgba(245,158,11,0.4); line-height:1; }
    .hitl-score-bar .zone { font-size:0.75rem; color:var(--text-muted); line-height:1.4; }
    .wa-preview {
      background: linear-gradient(180deg, #064e3b 0%, #022c22 100%); border-radius: 12px; padding: 16px;
      margin: 20px 0; font-family: 'JetBrains Mono', monospace; font-size: 0.75rem;
      color: #d1fae5; white-space: pre-wrap; line-height: 1.6;
      border: 1px solid rgba(16,185,129,0.2); box-shadow: 0 4px 15px rgba(0,0,0,0.5);
    }
    .wa-preview .wa-header { color: #6ee7b7; font-weight: 700; font-size:0.8rem; margin-bottom:10px; display:flex; align-items:center; gap:6px; }
    .hitl-actions { display: flex; gap: 12px; margin-top: 24px; }
    .hitl-actions .btn { flex: 1; justify-content: center; padding: 12px; font-size:0.85rem; height: 44px;}
    .replay-counter {
      display:flex; align-items:center; gap:8px; background:linear-gradient(90deg, rgba(139,92,246,0.15), rgba(139,92,246,0.05));
      border:1px solid rgba(139,92,246,0.3); border-radius:8px; padding:6px 12px;
      font-size:0.75rem; color:#c4b5fd; font-weight:700; box-shadow: 0 0 15px rgba(139,92,246,0.1);
    }
    ::-webkit-scrollbar { width: 6px; height: 6px; }
    ::-webkit-scrollbar-track { background: transparent; }
    ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 4px; }
    ::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.2); }
  </style>
</head>
<body>
  <!-- HITL Freeze Overlay -->
  <div id="hitlOverlay">
    <div class="hitl-card">
      <h2>⚠️ GUARDIAN — Awaiting Human Decision</h2>
      <div class="hitl-label">Context ID: <span id="hitlCtxId">—</span></div>

      <div class="hitl-field">
        <label>Pending Tool Call</label>
        <div class="val" id="hitlTool">—</div>
      </div>
      <div class="hitl-field">
        <label>Capability Tags</label>
        <div class="tags" id="hitlTags">—</div>
      </div>

      <div class="hitl-score-bar">
        <div class="score" id="hitlRiskPct">—%</div>
        <div class="zone">Risk Score<br><span style="color:#fbbf24">Gray Zone (55%–75%)</span><br>Autonomous decision not safe.</div>
      </div>

      <div class="hitl-field">
        <label>Counterfactual Impact (if ALLOWED)</label>
        <div class="cf" id="hitlCf">—</div>
      </div>

      <!-- Simulated WhatsApp message -->
      <div class="wa-preview">
        <div class="wa-header">📱 OpenClaw → WhatsApp Business</div>
        <div id="hitlWaMsg">—</div>
      </div>

      <div class="hitl-actions">
        <button class="btn btn-allow"  onclick="submitHITL('allow')">✅ [1] ALLOW</button>
        <button class="btn btn-shadow" onclick="submitHITL('shadow')">🔀 [3] SHADOW</button>
        <button class="btn btn-block"  onclick="submitHITL('block')">🚫 [2] BLOCK</button>
      </div>
    </div>
  </div>

  <div class="header">
    <div>
      <h1>🛡️ GUARDIAN Fleet — SOC War Room</h1>
      <div class="subtitle">WS: <span id="wsUrl"></span> &nbsp;|&nbsp; <span id="connStatus" style="color:#34d399">Connecting...</span></div>
    </div>
    <div class="domain-selector">
      <label>Target Domain</label>
      <select id="domainSelect" onchange="switchDomain()">
        <option value="enterprise">🏢 Enterprise HR/Finance  (Training)</option>
        <option value="finops">📈 Financial Algorithmic Trading  (Zero-Shot)</option>
        <option value="corpgov">🏛️ Multi-Agent Corp Governance  (Zero-Shot)</option>
      </select>
    </div>
  </div>

  <div class="status-bar" id="statusRow">
    <div class="badge badge-info"   id="badgeStep">Step 0</div>
    <div class="badge badge-ok"     id="badgeProd">✅ DB Intact</div>
    <div class="badge badge-ok"     id="badgeFork">No Fork</div>
    <div class="badge badge-ok"     id="badgeAtk">System Clean</div>
    <div class="badge badge-info"   id="badgeReward">Reward: 0.000</div>
    <div class="replay-counter" id="replayCounter" title="Human decisions logged for next GRPO training run">🧠 Replay Buffer: 0</div>
  </div>

  <div class="controls">
    <div class="control-group">
      <label>Intervention</label>
      <select id="intervention">
        <option>allow</option><option>shadow</option><option>rewrite</option>
        <option>interrogate</option><option>reduce_privs</option>
        <option>quarantine_tool</option><option>emergency_fork</option>
        <option>quarantine_agent</option>
      </select>
    </div>
    <div class="control-group">
      <label>Classified Threat</label>
      <select id="attack_type">
        <option value="">(None)</option>
        <option>authority_spoofing</option><option>prompt_injection</option>
        <option>approval_bypass</option><option>data_exfiltration</option>
        <option>confused_deputy</option><option>schema_drift_exploit</option>
        <option>rogue_internal_ai</option>
      </select>
    </div>
    <div class="control-group" style="flex:1; min-width:200px;">
      <label>Risk Score: <span id="riskVal" style="color:#60a5fa">0.30</span>
        <span id="zoneLabel" style="font-size:.68rem; color:#9ca3af; margin-left:6px;"></span>
      </label>
      <input type="range" id="riskSlider" min="0" max="1" step="0.05" value="0.3"
             oninput="onRiskChange(this.value)">
    </div>
    <div class="control-group" style="flex-direction:row; align-items:flex-end; gap:8px;">
      <button class="btn btn-reset" onclick="doReset()">↻ Reset</button>
      <button class="btn btn-step"  onclick="doStep()">▶ Execute Step</button>
      <button class="btn btn-clear" onclick="clearLog()">⌫ Clear</button>
      <button class="btn" style="background:rgba(139,92,246,.2);color:#a78bfa;border:1px solid rgba(139,92,246,.3)" onclick="simulateHITL()">⚠️ Demo HITL</button>
    </div>
  </div>

  <div class="grid">
    <div class="panel">
      <div class="panel-header">
        <span>📡 Telemetry & MCP Intercept Feed</span>
        <span style="color:#3b82f6" id="toolCount">0 Events</span>
      </div>
      <div class="event-feed" id="log">
        <div style="color:#6b7280;font-size:.78rem;text-align:center;margin-top:16px;">Awaiting enterprise telemetry hook...</div>
      </div>
    </div>

    <div style="display:flex; flex-direction:column; gap:18px;">
      <div class="panel">
        <div class="panel-header"><span>⚠️ Live Threat Assessment</span></div>
        <div class="threat-gauge-container">
          <svg viewBox="0 0 36 36" class="circular-chart">
            <path class="circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"/>
            <path class="circle" id="riskGauge" stroke="#10b981" stroke-dasharray="0, 100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"/>
            <text x="18" y="20.35" class="percentage" id="riskText">0%</text>
          </svg>
          <div style="margin-top:10px; font-size:.72rem; color:#9ca3af;" id="threatLabel">SYSTEM NORMAL</div>
        </div>
      </div>

      <div class="panel" style="flex:1;">
        <div class="panel-header"><span>🛡️ Last Observation</span></div>
        <div style="overflow-y:auto; max-height:180px;">
          <pre id="obsJson">{}</pre>
        </div>
      </div>
    </div>
  </div>

  <script>
    let ws, currentDomain = 'enterprise', pendingCtxId = null, replayCount = 0;
    const wsUrl = (location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+'/ws';
    document.getElementById('wsUrl').textContent = wsUrl;

    function connect() {
      ws = new WebSocket(wsUrl);
      ws.onopen  = ()=>{ setConn(true); addLog('System','Connected to MCP Gateway.',null,''); };
      ws.onclose = ()=>{ setConn(false); setTimeout(connect, 3000); };
      ws.onerror = ()=>{ addLog('Error','WebSocket dropped.',null,'attack'); };
      ws.onmessage = e => handleMsg(JSON.parse(e.data));
    }
    function setConn(ok){
      const el=document.getElementById('connStatus');
      el.textContent=ok?'🟢 Gateway Active':'🔴 Lost'; el.style.color=ok?'#34d399':'#f87171';
    }
    function send(m){ if(ws&&ws.readyState===1) ws.send(JSON.stringify(m)); }
    function doReset(){ send({type:'reset'}); clearLog(); addLog('System','Environment reset.'); }
    function doStep(){
      const risk = parseFloat(document.getElementById('riskSlider').value);
      // Check if risk is in gray zone — show HITL overlay for demo
      if(risk >= 0.55 && risk <= 0.75) {
        const tool = document.getElementById('attack_type').value || 'write_db';
        triggerHITLOverlay(risk, tool);
        return;
      }
      send({type:'step', action:{
        risk_score: risk,
        intervention: document.getElementById('intervention').value,
        attack_type: document.getElementById('attack_type').value||null,
        rollback_k: 2,
        reasoning: 'Manual SOC override'
      }});
    }
    function switchDomain(){
      const dom = document.getElementById('domainSelect').value;
      currentDomain = dom;
      send({type:'set_domain', domain:dom});
      clearLog();
      addLog('🌐 Domain Switch', 'Hot-swapped environment context → ' + dom.toUpperCase() + ' (zero-shot)', null, 'honeypot');
    }
    function clearLog(){ document.getElementById('log').innerHTML=''; document.getElementById('toolCount').textContent='0 Events'; }
    function onRiskChange(v){
      document.getElementById('riskVal').textContent = parseFloat(v).toFixed(2);
      const pct = Math.round(v*100);
      const zl = document.getElementById('zoneLabel');
      if(pct>=55&&pct<=75){ zl.textContent='⚠️ GRAY ZONE — HITL'; zl.style.color='#fbbf24'; }
      else if(pct>75){ zl.textContent='🚨 AUTO-BLOCK'; zl.style.color='#f87171'; }
      else { zl.textContent='✅ AUTO-ALLOW'; zl.style.color='#34d399'; }
    }
    function handleMsg(d){
      if(d.type==='step_result'){
        try{
          const log = JSON.parse(d.observation.action_log_json);
          if(log.length>0){
            const last=log[log.length-1];
            const style = d.observation.attack_active?'attack':(d.observation.fork_triggered?'honeypot':'');
            addLog(last.tool||'sys_call', JSON.stringify(last.params||{}), d.reward, style);
            if(d.observation.risk_history&&d.observation.risk_history.length>0)
              updateGauge(d.observation.risk_history[d.observation.risk_history.length-1]);
          }
        }catch(e){}
      } else if(d.type==='error'){
        addLog('Error', d.message, null, 'attack');
      }
      const obs=d.observation;
      if(obs){
        document.getElementById('obsJson').textContent=JSON.stringify(obs,null,2);
        setB('badgeStep','Step '+obs.current_step,'badge-info');
        setB('badgeProd',obs.production_intact?'✅ DB INTACT':'❌ BREACHED',obs.production_intact?'badge-ok':'badge-bad');
        setB('badgeFork',obs.fork_triggered?'🔀 HONEYPOT':'NO FORK',obs.fork_triggered?'badge-warn':'badge-ok');
        setB('badgeAtk',obs.attack_active?'⚠️ ATTACK':'CLEAN',obs.attack_active?'badge-bad':'badge-ok');
      }
      if(d.reward!==undefined) setB('badgeReward','R: '+Number(d.reward).toFixed(4),'badge-info');
    }
    function addLog(title, detail, reward, styleClass=''){
      const feed=document.getElementById('log');
      const time=new Date().toISOString().substring(11,23);
      const div=document.createElement('div');
      div.className='event-card '+(styleClass||'');
      div.innerHTML=`
        <div style="display:flex;justify-content:space-between;color:#9ca3af; margin-bottom:4px;">
          <span style="font-weight:700;color:#e5e7eb">${title}</span>
          <span style="color:#6b7280">${time}${reward!=null?' | R:'+Number(reward).toFixed(3):''}</span>
        </div>
        <div style="color:#60a5fa;word-break:break-all">${detail}</div>
      `;
      feed.prepend(div);
      document.getElementById('toolCount').textContent=feed.children.length+' Events';
    }
    function setB(id,txt,cls){ const b=document.getElementById(id); b.textContent=txt; b.className='badge '+cls; }
    function updateGauge(val){
      const pct=Math.round(val*100);
      document.getElementById('riskText').textContent=pct+'%';
      let color='#10b981',label='SYSTEM NORMAL';
      if(pct>55&&pct<=75){ color='#a78bfa'; label='⚠️ GRAY ZONE — AWAITING HUMAN'; }
      else if(pct>40){ color='#f59e0b'; label='ELEVATED RISK'; }
      if(pct>75){ color='#ef4444'; label='CRITICAL THREAT'; }
      const path=document.getElementById('riskGauge');
      path.setAttribute('stroke-dasharray',`${pct}, 100`);
      path.setAttribute('stroke',color);
      const lbl=document.getElementById('threatLabel');
      lbl.textContent=label; lbl.style.color=color;
    }

    /* ── HITL Overlay ─────────────────────────────── */
    function triggerHITLOverlay(risk, tool){
      pendingCtxId = 'demo-' + Math.random().toString(36).substr(2,8);
      const pct = Math.round(risk*100);
      const counterfactuals = {
        'override_margin_limits': 'Margin reqs zeroed — uncollateralized positions ~$50M accumulate.',
        'modify_iam_policy': 'Rogue agent gains persistent admin privileges across all enterprise systems.',
        'data_exfiltration': 'Full employee PII (14K records) exfiltrated to external endpoint.',
        'modify_compliance_threshold': 'All future board approvals bypass review automatically.',
        'write_db': 'Production DB mutated without rollback capability — data integrity compromised.',
      };
      const cf = counterfactuals[tool] || 'System state permanently corrupted with high blast radius.';
      const tags = risk > 0.6 ? '[STATE_MOD=True|PRIV_ESC=True|EXT_COMM=False|FINANCIAL=Critical]'
                               : '[STATE_MOD=True|PRIV_ESC=False|EXT_COMM=True|FINANCIAL=High]';
      const waMsg = `🚨 *GUARDIAN Escalation — Decision Required*\n${'━'.repeat(30)}\nDomain: ${currentDomain.toUpperCase()}\nTool: \`${tool}()\`\nCapability: \`${tags}\`\nRisk Score: ${pct}% _(Gray Zone — Ambiguous)_\n\nCounterfactual: _${cf}_\n${'━'.repeat(30)}\nReply:\n[1] ALLOW  [2] BLOCK  [3] SHADOW\n\nContext: \`${pendingCtxId}\``;
      document.getElementById('hitlCtxId').textContent = pendingCtxId;
      document.getElementById('hitlTool').textContent = tool + '()';
      document.getElementById('hitlTags').textContent = tags;
      document.getElementById('hitlRiskPct').textContent = pct + '%';
      document.getElementById('hitlCf').textContent = cf;
      document.getElementById('hitlWaMsg').textContent = waMsg;
      document.getElementById('hitlOverlay').classList.add('active');
      updateGauge(risk);
      addLog('⚠️ HITL Escalation', `Gray-zone risk (${pct}%) — execution FROZEN. Awaiting human decision.`, null, 'hitl');
    }
    function simulateHITL(){
      const tools = ['override_margin_limits','modify_iam_policy','data_exfiltration','write_db'];
      const tool = tools[Math.floor(Math.random()*tools.length)];
      triggerHITLOverlay(0.62 + Math.random()*0.12, tool);
    }
    async function submitHITL(decision){
      document.getElementById('hitlOverlay').classList.remove('active');
      const labels = {allow:'✅ ALLOWED (Production)', block:'🚫 BLOCKED (Quarantined)', shadow:'🔀 SHADOWED (→ Honeypot)'};
      addLog('🧠 Human Decision: ' + decision.toUpperCase(), `Context ${pendingCtxId} resolved — ${labels[decision]}`, null, decision==='allow'?'':'honeypot');
      // POST to real endpoint
      try {
        const r = await fetch('/hitl/decision', {
          method:'POST', headers:{'Content-Type':'application/json'},
          body: JSON.stringify({context_id: pendingCtxId, decision})
        });
        const data = await r.json();
        replayCount = data.replay_buffer_total || replayCount + 1;
        document.getElementById('replayCounter').textContent = '🧠 Replay Buffer: ' + replayCount;
        addLog('📝 Replay Buffer Updated', `Ground-truth entry logged. GRPO training queue: ${replayCount} examples.`, null, 'hitl');
      } catch(e) {
        replayCount++;
        document.getElementById('replayCounter').textContent = '🧠 Replay Buffer: ' + replayCount;
      }
      // Now send the actual step with the human-decided intervention
      const ivMap = {allow:'allow', block:'quarantine_agent', shadow:'shadow'};
      send({type:'step', action:{
        risk_score: parseFloat(document.getElementById('riskSlider').value),
        intervention: ivMap[decision],
        attack_type: document.getElementById('attack_type').value||null,
        rollback_k: 2,
        reasoning: `Human HITL decision: ${decision} (context: ${pendingCtxId})`
      }});
      pendingCtxId = null;
    }
    connect();
    // Periodically refresh replay counter from server
    setInterval(async ()=>{
      try{
        const r=await fetch('/hitl/replay_stats');
        const d=await r.json();
        if(d.total_entries!==undefined){
          replayCount=d.total_entries;
          document.getElementById('replayCounter').textContent='🧠 Replay Buffer: '+replayCount;
        }
      }catch(e){}
    }, 10000);
  </script>
</body>
</html>"""

# ── Entrypoint ────────────────────────────────────────────────────────────────

def main() -> None:
    """Called by `guardian-server` console script (pyproject.toml entry point)."""
    port = int(os.getenv("PORT", "8000"))
    host = os.getenv("HOST", "0.0.0.0")
    log.info(f"Starting uvicorn on {host}:{port}")
    uvicorn.run("server.app:app", host=host, port=port, reload=False)


if __name__ == "__main__":
    main()
